const COINGECKO_ASSET_PLATFORMS = [
  { id: 'factom', chain_identifier: null, name: 'Factom', shortname: '' },
  {
    id: 'openledger',
    chain_identifier: null,
    name: 'OpenLedger',
    shortname: '',
  },
  { id: 'cosmos', chain_identifier: null, name: 'Cosmos', shortname: '' },
  {
    id: 'binancecoin',
    chain_identifier: null,
    name: 'Binance Coin',
    shortname: '',
  },
  {
    id: 'metaverse-etp',
    chain_identifier: null,
    name: 'Metaverse ETP',
    shortname: '',
  },
  { id: 'nem', chain_identifier: null, name: 'NEM', shortname: '' },
  { id: 'icon', chain_identifier: null, name: 'ICON', shortname: '' },
  { id: 'waves', chain_identifier: null, name: 'Waves', shortname: '' },
  { id: 'kava', chain_identifier: null, name: 'Kava', shortname: '' },
  { id: 'stratis', chain_identifier: null, name: 'Stratis', shortname: '' },
  { id: 'algorand', chain_identifier: null, name: 'Algorand', shortname: '' },
  { id: 'nuls', chain_identifier: null, name: 'Nuls', shortname: '' },
  { id: 'qtum', chain_identifier: null, name: 'Qtum', shortname: '' },
  { id: 'stellar', chain_identifier: null, name: 'Stellar', shortname: '' },
  { id: 'nxt', chain_identifier: null, name: 'NXT', shortname: '' },
  { id: 'ardor', chain_identifier: null, name: 'Ardor', shortname: '' },
  { id: 'ontology', chain_identifier: null, name: 'Ontology', shortname: '' },
  { id: 'eos', chain_identifier: null, name: 'EOS', shortname: '' },
  { id: 'polkadot', chain_identifier: null, name: 'Polkadot', shortname: '' },
  { id: 'vechain', chain_identifier: null, name: 'VeChain', shortname: '' },
  { id: 'omni', chain_identifier: null, name: 'Omni', shortname: '' },
  {
    id: 'counterparty',
    chain_identifier: null,
    name: 'Counterparty',
    shortname: '',
  },
  { id: 'klay-token', chain_identifier: null, name: 'Klaytn', shortname: '' },
  { id: 'chiliz', chain_identifier: null, name: 'Chiliz', shortname: '' },
  { id: 'bitshares', chain_identifier: null, name: 'BitShares', shortname: '' },
  { id: 'neo', chain_identifier: null, name: 'NEO', shortname: '' },
  { id: 'super-zero', chain_identifier: null, name: 'Sero', shortname: '' },
  {
    id: 'ethereum-classic',
    chain_identifier: null,
    name: 'Ethereum Classic',
    shortname: '',
  },
  { id: 'tron', chain_identifier: null, name: 'TRON', shortname: '' },
  { id: 'tezos', chain_identifier: null, name: 'Tezos', shortname: '' },
  { id: 'komodo', chain_identifier: null, name: 'Komodo', shortname: '' },
  {
    id: 'rootstock',
    chain_identifier: null,
    name: 'Rootstock RSK',
    shortname: '',
  },
  { id: 'achain', chain_identifier: null, name: 'Achain', shortname: '' },
  { id: 'solana', chain_identifier: null, name: 'Solana', shortname: '' },
  { id: 'vite', chain_identifier: null, name: 'Vite', shortname: '' },
  { id: 'telos', chain_identifier: null, name: 'Telos', shortname: '' },
  { id: 'gochain', chain_identifier: null, name: 'GoChain', shortname: '' },
  { id: 'wanchain', chain_identifier: null, name: 'Wanchain', shortname: '' },
  { id: 'enq-enecuum', chain_identifier: null, name: 'Enecuum', shortname: '' },
  { id: 'mdex', chain_identifier: null, name: 'Mdex', shortname: '' },
  { id: 'fantom', chain_identifier: 250, name: 'Fantom', shortname: '' },
  {
    id: 'binance-smart-chain',
    chain_identifier: 56,
    name: 'Binance Smart Chain',
    shortname: 'BSC',
  },
  { id: 'ethereum', chain_identifier: 1, name: 'Ethereum', shortname: '' },
  { id: 'xdai', chain_identifier: 100, name: 'xDAI', shortname: '' },
  {
    id: 'bitcoin-cash',
    chain_identifier: null,
    name: 'Simple Ledger Protocol (Bitcoin Cash)',
    shortname: 'SLP',
  },
  {
    id: 'okex-chain',
    chain_identifier: 66,
    name: 'OKExChain',
    shortname: 'OKEx',
  },
  { id: 'tomochain', chain_identifier: 88, name: 'TomoChain', shortname: '' },
  {
    id: 'avalanche',
    chain_identifier: 43114,
    name: 'Avalanche',
    shortname: 'AVAX',
  },
  { id: 'zilliqa', chain_identifier: null, name: 'Zilliqa', shortname: '' },
  { id: 'iotex', chain_identifier: null, name: 'IoTeX', shortname: 'iotex' },
  {
    id: 'polygon-pos',
    chain_identifier: 137,
    name: 'Polygon POS',
    shortname: 'MATIC',
  },
  {
    id: 'huobi-token',
    chain_identifier: 128,
    name: 'Huobi ECO Chain Mainnet',
    shortname: 'HECO',
  },
  { id: 'cardano', chain_identifier: null, name: 'Cardano', shortname: '' },
  { id: 'terra', chain_identifier: null, name: 'Terra', shortname: '' },
  { id: 'celo', chain_identifier: 42220, name: 'Celo', shortname: 'celo' },
  {
    id: 'harmony-shard-0',
    chain_identifier: 1666600000,
    name: 'Harmony Shard 0',
    shortname: 'Harmony Shard 0',
  },
];

export { COINGECKO_ASSET_PLATFORMS };
